### ISSUE TITLE
Infinite for loop : break/next issue ?

### ISSUE THREAD

**Issue by baptroux** [olugovoy/climatedice#2]
Hi,

I am using this model (the DICE2016inR_standalone.Rmd file)as a baseline for my own model and I face some difficulties that also concern this version. 
When I knit the markdown, it takes a lot of time (which is logical given the amount of calculations) but it generates the output efficiently. Yet, when I run it chunk by chunk, I find that the optimization chunk (at system.time line 937) runs infinitely. The part that is concerned with this problem is most probably the for loop on time at line 736. When I print i while running it, I find out that the loop never stops and goes over and over (when it reaches i=NT, it starts again from i=1). Stopping the run gives a "no break/jump to higher level" message.
Although it allows me to obtain the output, I suspect this infinite loop is the reason why it takes so long to knit.

Could you help me with this ?

**Comment by olugovoy** [comment]
Hi there,
The line #937 calls a solver from *NlcOptim* package. The solver evaluates the *fOBJ* function iteratively until one of the terminal conditions met. There are several of them: ` maxIter = 1e3`, `tolX = 1e-3`, etc... see below and help to the `?NlcOptim::solnl` function.  
` ss1 <- NlcOptim::solnl( 
    X = x_start,   
    objfun = fOBJ,   
    # confun = confun,  
    lb = lb_nofx,  
    ub = ub_nofx,  
    maxIter = 1e3,  
    tolX = 1e-3,  
    tolFun = 1e-3,  
    tolCon = 1e-3)`   
I have just tried to run the code. It takes 74 seconds to solve the model on my computer with the provided starting values `x_start`. Have you changed the starting values or any equations? It may affect the time. To try if the solver runs, try to set the maxIter = 1 or 10 and see if it will finish. To check the objective for an infinite loop, try `fOBJ(x_start)` which gives `-4346.221` in the example if no changes. If you have the same output, then `fOBJ` works fine, the problem is with the solver, why it takes too much time. Also (since it runs when knitted) there might be some conflicts with names/environmental variables in the memory or uploaded packages - removing everything from memory (rm(list = ls(all.names = T))) with following restarting of R may help then.

Alternatively you can solve the model with a simple iterative algorithm - see the "Solving without a solver" part (lines #991-1100). It takes a bit more time but you can see the convergence process and stop the algorithm any time (play with `niter1` and `niter2`).

**Comment by baptroux** [comment]
Hi,
Thanks again. Your comments help a lot.
I tried everything you said both on the original model and on my own model to figure out where was the problem. For your information, my model relies on rank-dependent analysis, i.e I add a rank (in income) variable in the individual functions (income per capita, consumption per capita, individual utility) but the optimization program is entirely similar on its control variables.
 The original version runs quite fast indeed. But what worries me is that despite changing to maxIter=1, I still have a loop with multiple iterations (that I see with a print(i) command) before the chunk runs. Same in my own model except that it doesn't run even after 15+ minutes. It seems like it doesn't take the maxIter command into consideration.
I ran the fOBJ(x_start) command on the two models and obtained -4346.221 in the original one and another finite value (11230...) in mine. So the fOBJ works fine, the problem is the solver.
Also, I have tried to use the simple iterative algorithm and even if I don't meet this iterative issue, I get an error message saying that ss1 (the optimization output of the other solver) is missing, which is normal as I couldn't run the other solver. Also, I feel like the alternative algorithm is not sufficient to generate plots further.
EDIT : My own code finally ran after some time, but it is normal given the additional computations due to the new variable r. Your comments helped my thesis in a way you can't imagine.
Thank you so much
